---
- hosts: all
  sudo: yes
  vars_files:
    - ./vars/base-env.yml
  roles:
    - common

- hosts: zookeeper
  sudo: yes
  vars_files:
    - ./vars/base-env.yml
  roles:
    - jdk8
    - zookeeper

- hosts: nodelab2
  sudo: yes
  vars_files:
    - ./vars/base-env.yml
  roles:
    - jdk8
    - {role: "spark2", spark_is_master: "true"}

- hosts: nodelab1
  sudo: yes
  vars_files:
    - ./vars/base-env.yml
  roles:
    - jdk8
    - kafka
    # # - KafkaOffsetMonitor
    - {role: "spark2", spark_is_slave: "true"}

- hosts: nodelab3
  sudo: yes
  vars_files:
    - ./vars/base-env.yml
  roles:
    - jdk8
    - filebeat
    - {role: "spark2", spark_is_slave: "true"}

- hosts: nodelab4
  sudo: yes
  vars_files:
    - ./vars/base-env.yml

  roles:
    - filebeat
    - openresty
    - app
    - redis
