---
- hosts: all
  sudo: yes
  vars_files:
    - ./vars/base-env.yml
  roles:
    - common

- hosts: zookeeper
  sudo: yes
  vars_files:
    - ./vars/base-env.yml
  vars:
    - user: zookeeper
    - user_group: zookeeper
    ##python -c 'import crypt; print crypt.crypt("cloud", "$1$SomeSalt$")'
    - password: $1$SomeSalt$15avH4qSlfRSEvC0bIn2./
  roles:
    - jdk8
    - zookeeper


- hosts: nodelab1
  sudo: yes
  vars_files:
    - ./vars/base-env.yml
  vars:
    - user: kafka
    - user_group: kafka
    ##python -c 'import crypt; print crypt.crypt("cloud", "$1$SomeSalt$")'
    - password: $1$SomeSalt$15avH4qSlfRSEvC0bIn2./
  roles:
    - jdk8
    - kafka
    # # - KafkaOffsetMonitor
    - {role: "spark2", spark_is_slave: "true"}

- hosts: nodelab2
  sudo: yes
  vars_files:
    - ./vars/base-env.yml
  roles:
    - filebeat
    - {role: "spark2", spark_is_master: "true"}


- hosts: nodelab3
  sudo: yes
  vars_files:
    - ./vars/base-env.yml
  roles:
    - filebeat
    - {role: "spark2", spark_is_slave: "true"}
